# __Date and TimeDelta in Pandas__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Date and TimeDelta in Pandas
- Date Handling in Pandas
  * Extracting Components from Dates
- Timedelta in Pandas
  * Creating a Timedelta
  * Performing Arithmetic Operations
  * Resampling Time Series Data
- Categorical Data Handling
  * Creating a Categorical Variable
  * Counting Occurrences of Each Category
  * Creating Dummy Variables
  * Label Encoding

##  __1. Date and TimeDelta in Pandas__

In Pandas, the datetime module provides robust functionality for handling date and time data, while the timedelta class allows for convenient manipulation of time intervals. This combination is particularly useful for time-based analysis and working with temporal data in a DataFrame.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_04_Working_with_Pandas/3_Date_and_TimeDelta_in_Pandas/Date_and_Time.png)

## __2. Date Handling in Pandas__
#### Creating a Date Range:

- The date_range function is used to generate a sequence of dates within a specified range.
- It is a powerful tool for creating time indices or date columns in a DataFrame.
- The start and end parameters define the range, while freq determines the frequency, such as daily (D) or monthly (M).

In [6]:
import pandas as pd

# Generate a date range
date_range = pd.date_range(start='2023-01-01', end='2024-01-10', freq='MS')
print(date_range)

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01',
               '2024-01-01'],
              dtype='datetime64[us]', freq='MS')

### __2.1 Extracting Components from Dates__

Pandas provides the dt accessor to extract various components (Example: day, month, year) from a date column in a DataFrame. This is valuable for time-based analysis when specific date attributes need to be considered.

In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame with a 'Date' column
data = {'Date': ['2023-01-01', '2023-02-15', '2023-03-20']}
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date'])

# Extracting day, month, and year information
df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

# Displaying the DataFrame with extracted information
print(df[['Date', 'Day', 'Month', 'Year']])

        Date  Day  Month  Year
0 2023-01-01    1      1  2023
1 2023-02-15   15      2  2023
2 2023-03-20   20      3  2023

In [11]:
# Extracting weekday and weekend information
df = pd.DataFrame({'Date': pd.date_range(start='2023-01-01', periods=5)})
df['Weekday'] = df['Date'].dt.weekday
df['IsWeekend'] = df['Date'].dt.weekday // 5 == 1
print(df[['Date', 'Weekday', 'IsWeekend']])

        Date  Weekday  IsWeekend
0 2023-01-01        6       True
1 2023-01-02        0      False
2 2023-01-03        1      False
3 2023-01-04        2      False
4 2023-01-05        3      False

In [27]:
# Shifting dates forward or backward
df['Date'] = pd.to_datetime(df['Date'])
df['PreviousDate'] = df['Date'] - pd.Timedelta(days=1)
df['NextDate'] = df['Date'] + pd.Timedelta(days=1)
print(df[['Date', 'PreviousDate', 'NextDate']])

        Date PreviousDate   NextDate
0 2023-01-01   2022-12-31 2023-01-02
1 2023-01-02   2023-01-01 2023-01-03
2 2023-01-03   2023-01-02 2023-01-04
3 2023-01-04   2023-01-03 2023-01-05
4 2023-01-05   2023-01-04 2023-01-06

## __3. Timedelta in Pandas__
### __3.1 Creating a Timedelta__

- The Timedelta class in Pandas represents a duration or the difference between two dates or times.
- It can be created by specifying the desired duration, such as days, hours, or minutes.

In [31]:
import pandas as pd

data = {
    'Date': pd.date_range(start='2023-01-01', periods=30, freq='h'),
    'Value1': range(30),
    'Value2': range(10, 40)
}
df = pd.DataFrame(data)

# Creating a timedelta of 3 days
delta = pd.Timedelta(days=3)
delta

Timedelta('3 days 00:00:00')

### __3.2 Performing Arithmetic Operations__

Timedelta objects can be used to perform arithmetic operations on dates. For example, adding a timedelta to a date results in a new date. This is useful for calculating future or past dates based on a given time interval.

In [32]:
# Performing arithmetic operations with timedeltas
df['Date'] = pd.to_datetime(df['Date'])
df['FutureDate'] = df['Date'] + pd.Timedelta(weeks=2, days=3, hours=12)
print(df[['Date', 'FutureDate']])

                  Date          FutureDate
0  2023-01-01 00:00:00 2023-01-18 12:00:00
1  2023-01-01 01:00:00 2023-01-18 13:00:00
2  2023-01-01 02:00:00 2023-01-18 14:00:00
3  2023-01-01 03:00:00 2023-01-18 15:00:00
4  2023-01-01 04:00:00 2023-01-18 16:00:00
5  2023-01-01 05:00:00 2023-01-18 17:00:00
6  2023-01-01 06:00:00 2023-01-18 18:00:00
7  2023-01-01 07:00:00 2023-01-18 19:00:00
8  2023-01-01 08:00:00 2023-01-18 20:00:00
9  2023-01-01 09:00:00 2023-01-18 21:00:00
10 2023-01-01 10:00:00 2023-01-18 22:00:00
11 2023-01-01 11:00:00 2023-01-18 23:00:00
12 2023-01-01 12:00:00 2023-01-19 00:00:00
13 2023-01-01 13:00:00 2023-01-19 01:00:00
14 2023-01-01 14:00:00 2023-01-19 02:00:00
15 2023-01-01 15:00:00 2023-01-19 03:00:00
16 2023-01-01 16:00:00 2023-01-19 04:00:00
17 2023-01-01 17:00:00 2023-01-19 05:00:00
18 2023-01-01 18:00:00 2023-01-19 06:00:00
19 2023-01-01 19:00:00 2023-01-19 07:00:00
20 2023-01-01 20:00:00 2023-01-19 08:00:00
21 2023-01-01 21:00:00 2023-01-19 09:00:00
22 2023-01-01 22:00:00 2023-01-19 10:00:00
23 2023-01-01 23:00:00 2023-01-19 11:00:00
24 2023-01-02 00:00:00 2023-01-19 12:00:00
25 2023-01-02 01:00:00 2023-01-19 13:00:00
26 2023-01-02 02:00:00 2023-01-19 14:00:00
27 2023-01-02 03:00:00 2023-01-19 15:00:00
28 2023-01-02 04:00:00 2023-01-19 16:00:00
29 2023-01-02 05:00:00 2023-01-19 17:00:00

### __3.3 Resampling Time Series Data__

Time series data often comes with irregular time intervals. Resampling is the process of changing the frequency of the time series data, either by upsampling (increasing frequency) or downsampling (decreasing frequency).

In [34]:
# Resampling time series data
# df.set_index('Date', inplace=True)
df_resampled = df.select_dtypes(include='number').resample('D').sum()
print(df_resampled)
df

            Value1  Value2
Date
2023-01-01     276     516
2023-01-02     159     219

                     Value1  Value2          FutureDate
Date
2023-01-01 00:00:00       0      10 2023-01-18 12:00:00
2023-01-01 01:00:00       1      11 2023-01-18 13:00:00
2023-01-01 02:00:00       2      12 2023-01-18 14:00:00
2023-01-01 03:00:00       3      13 2023-01-18 15:00:00
2023-01-01 04:00:00       4      14 2023-01-18 16:00:00
2023-01-01 05:00:00       5      15 2023-01-18 17:00:00
2023-01-01 06:00:00       6      16 2023-01-18 18:00:00
2023-01-01 07:00:00       7      17 2023-01-18 19:00:00
2023-01-01 08:00:00       8      18 2023-01-18 20:00:00
2023-01-01 09:00:00       9      19 2023-01-18 21:00:00
2023-01-01 10:00:00      10      20 2023-01-18 22:00:00
2023-01-01 11:00:00      11      21 2023-01-18 23:00:00
2023-01-01 12:00:00      12      22 2023-01-19 00:00:00
2023-01-01 13:00:00      13      23 2023-01-19 01:00:00
2023-01-01 14:00:00      14      24 2023-01-19 02:00:00
2023-01-01 15:00:00      15      25 2023-01-19 03:00:00
2023-01-01 16:00:00      16      26 2023-01-19 04:00:00
2023-01-01 17:00:00      17      27 2023-01-19 05:00:00
2023-01-01 18:00:00      18      28 2023-01-19 06:00:00
2023-01-01 19:00:00      19      29 2023-01-19 07:00:00
2023-01-01 20:00:00      20      30 2023-01-19 08:00:00
2023-01-01 21:00:00      21      31 2023-01-19 09:00:00
2023-01-01 22:00:00      22      32 2023-01-19 10:00:00
2023-01-01 23:00:00      23      33 2023-01-19 11:00:00
2023-01-02 00:00:00      24      34 2023-01-19 12:00:00
2023-01-02 01:00:00      25      35 2023-01-19 13:00:00
2023-01-02 02:00:00      26      36 2023-01-19 14:00:00
2023-01-02 03:00:00      27      37 2023-01-19 15:00:00
2023-01-02 04:00:00      28      38 2023-01-19 16:00:00
2023-01-02 05:00:00      29      39 2023-01-19 17:00:00

## __4. Categorical Data Handling__

### __4.1 Creating a Categorical Variable__
Pandas provides the categorical class to create a categorical variable. Categorical variables are useful when dealing with data that can be divided into distinct, non-numeric categories.

In [38]:
import pandas as pd

# Creating a categorical variable
categories = ['Low', 'Medium', 'High']
values = ['Low', 'Medium', 'High', 'Low', 'High']
cat_variable = pd.Categorical(values, categories=categories, ordered=True)
print(cat_variable)

['Low', 'Medium', 'High', 'Low', 'High']
Categories (3, str): ['Low' < 'Medium' < 'High']

### __4.2 Counting Occurrences of Each Category__
The value_counts() method is used to count the occurrences of each category in a categorical column of a DataFrame.

In [33]:
# Assuming 'df' is your DataFrame with a 'Category' column
df = pd.DataFrame({'Category': ['A', 'B', 'A', 'C', 'B', 'A']})

# Counting occurrences of each category
category_counts = df['Category'].value_counts()
print(category_counts)

Category
A    3
B    2
C    1
Name: count, dtype: int64

### __4.3 Creating Dummy Variables__

When working with machine learning models or statistical analyses, creating dummy variables is often necessary to represent categorical data numerically. The get_dummies function creates binary columns for each category, effectively converting categorical data into a numerical format.

In [39]:
# Assuming 'df' is your DataFrame with a 'Category' column
df = pd.DataFrame({'Category': ['A', 'B', 'A', 'C', 'B', 'A']})

# Creating dummy variables for categorical data
dummy_variables = pd.get_dummies(df['Category'], prefix='Categorys')
print(dummy_variables)

   Categorys_A  Categorys_B  Categorys_C
0         True        False        False
1        False         True        False
2         True        False        False
3        False        False         True
4        False         True        False
5         True        False        False

### __4.4 Label Encoding__

Another way to handle categorical data is through label encoding, where each category is assigned a unique numerical label. This is useful in scenarios where ordinal relationships exist between categories.

In [42]:
# Assuming 'df' is your DataFrame with a 'Category' column
df = pd.DataFrame({'Category': ['A', 'B', 'A', 'C', 'B', 'A']})

# Label Encoding
df['Category_LabelEncoded'] = df['Category'].astype('category').cat.codes
print(df[['Category', 'Category_LabelEncoded']])

  Category  Category_LabelEncoded
0        A                      0
1        B                      1
2        A                      0
3        C                      2
4        B                      1
5        A                      0

# __Assisted Practice__

## __Problem Statement:__
Analyze the housing dataset with a focus on handling date and categorical data to gain insights into house sales over time and the influence of house characteristics on its price.

## __Steps to Perform:__
- Convert the __YearBuilt__ and __YearRemodAdd__ columns to datetime format (if not converted)
- Extract useful components from the date like the year, month, or day
- Calculate the time difference between the year the house was built and the year it was remodeled
- Perform necessary arithmetic operations
- Count the number of occurrences of each category in categorical features
- Create dummy variables for categorical variables

In [52]:
data=pd.read_csv('housing_data.csv')
df=pd.DataFrame(data)
df['YearBuilt']=pd.to_datetime(df['YearBuilt'])
df['YearRemodAdd']=pd.to_datetime(df['YearRemodAdd'])
print(df['YearBuilt'].dt.day)
print(df['YearBuilt'].dt.month)
print(df['YearBuilt'].dt.year)

0       1
1       1
2       1
3       1
4       1
       ..
1455    1
1456    1
1457    1
1458    1
1459    1
Name: YearBuilt, Length: 1460, dtype: int32
0       1
1       1
2       1
3       1
4       1
       ..
1455    1
1456    1
1457    1
1458    1
1459    1
Name: YearBuilt, Length: 1460, dtype: int32
0       1970
1       1970
2       1970
3       1970
4       1970
        ...
1455    1970
1456    1970
1457    1970
1458    1970
1459    1970
Name: YearBuilt, Length: 1460, dtype: int32

In [56]:
print(df['YearBuilt']-df['YearRemodAdd'])

0                  0 days 00:00:00
1                  0 days 00:00:00
2      -1 days +23:59:59.999999999
3      -1 days +23:59:59.999999945
4                  0 days 00:00:00
                   ...
1455   -1 days +23:59:59.999999999
1456   -1 days +23:59:59.999999990
1457   -1 days +23:59:59.999999935
1458   -1 days +23:59:59.999999954
1459               0 days 00:00:00
Length: 1460, dtype: timedelta64[ns]

In [57]:
print(df['SaleType'].value_counts())

SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

In [60]:
dummies=pd.get_dummies(df['SaleType'],prefix="category_")
dummies

,category__COD,category__CWD,category__Con,category__ConLD,category__ConLI,category__ConLw,category__New,category__Oth,category__WD
0,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
1455,False,False,False,False,False,False,False,False,True
1456,False,False,False,False,False,False,False,False,True
1457,False,False,False,False,False,False,False,False,True
1458,False,False,False,False,False,False,False,False,True
1459,False,False,False,False,False,False,False,False,True